# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20170114_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
