# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_partner_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('ko', '한식'), ('cn', '중식'), ('jp', '일식')], default='ko', max_length=10),
        ),
    ]
